variables:
  KUBECONFIG: /home/gitlab-runner/.kube/oregon-b.kubeconfig

monthly:
  tags:
    - oregon-b-shell
  only:
    variables:
      - $MONTHLY
  script:
    - ./k8s-nbconvert.sh jupyter-notebooks/monthly-performance.ipynb commit-month
    - curl ${DMS_URL}

quarterly:
  tags:
    - oregon-b-shell
  only:
    variables:
      - $QUARTERLY
  script:
    - ./k8s-nbconvert.sh jupyter-notebooks/quarterly-performance.ipynb commit-quarter
