monthly:
  tags:
    - oregon-b-shell
  only:
    variables:
      - $MONTHLY
  script:
    - ./k8s-nbconvert.sh jupyter-notebooks/monthly-performance.ipynb commit-month

quarterly:
  tags:
    - oregon-b-shell
  only:
    variables:
      - $QUARTERLY
  script:
    - ./k8s-nbconvert.sh jupyter-notebooks/quarterly-performance.ipynb commit-quarter
